# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2
language: objective-c
podfile: Example/Podfile
before_install:
- gem install cocoapods
- pod repo update
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/Ohana.xcworkspace -scheme TravisCIScheme -sdk iphonesimulator10.2 -destination "id=E40727B3-41FB-4D6E-B4CB-BFA87109EB12" ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
